{% set name = "gromacswrapper" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f196666ff22c97e51068c36393d447d259bd067dd22b3e22393ab61e5892a855

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - numkit
    - numpy >=1.0
    - python >={{ python_min }}

test:
  imports:
    - gromacs
    - gromacs.fileformats
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Becksteinlab/GromacsWrapper
  summary: A Python wrapper around the Gromacs tools.
  doc_url: https://gromacswrapper.readthedocs.io/
  dev_url: https://github.com/Becksteinlab/GromacsWrapper
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  description: |
    GromacsWrapper is a Python package that wraps system calls to GROMACS
    tools into thin classes. This allows for fairly seamless integration
    of the GROMACS tools into Python scripts.

extra:
  recipe-maintainers:
    - orbeckst
    - njzjz
